version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: asterix_postgres
    environment:
      POSTGRES_DB: asterix_db
      POSTGRES_USER: asterix_user
      POSTGRES_PASSWORD: asterix_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - asterix_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: asterix_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - asterix_network

  # FastAPI Backend
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: asterix_backend
    environment:
      - DATABASE_URL=postgresql://asterix_user:asterix_password@postgres:5432/asterix_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=your-secret-key-change-in-production
      - NASA_API_KEY=${NASA_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ../backend:/app
    networks:
      - asterix_network

  # Next.js Frontend
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: asterix_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ../frontend:/app
      - /app/node_modules
    networks:
      - asterix_network

volumes:
  postgres_data:
  redis_data:

networks:
  asterix_network:
    driver: bridge
